const optionsRubros = [
  { value: 'ACEITES' },
  { value: 'AEROS  DESO - DESINFECT' },
  { value: 'Alcohol' },
  { value: 'ALIMENTACIÓN SALUDABLE' },
  { value: 'ALIMENTO BALANCEADO' },
  { value: 'BATERÍAS' },
  { value: 'BEBIDA A BASE DE HIERBAS' },
  { value: 'BEBIDA APERITIVO' },
  { value: 'BEBIDA READY TO DRINK' },
  { value: 'BEBIDAS CERVEZAS' },
  { value: 'Bonificaciones' },
  { value: 'CIGARRILLOS' },
  { value: 'COLONIAS' },
  { value: 'COSMETICOS' },
  { value: 'CUIDADO DE LA SALUD' },
  { value: 'CUIDADO DEL BEBE' },
  { value: 'CUIDADO DEL CABELLO' },
  { value: 'CUIDADO DENTAL' },
  { value: 'CUIDADO FEMENINO' },
  { value: 'DESODORANTE PARA PISOS' },
  { value: 'Espumante' },
  { value: 'DESODORANTES' },
  { value: 'DETERGENTES' },
  { value: 'Electronica' },
  { value: 'Encendedores' },
  { value: 'ENCURTIDO' },
  { value: 'Energizantes' },
  { value: 'ESPECIAS' },
  { value: 'ESPUMAS Y GELES DE AFEITAR' },
  { value: 'GOLOSINAS' },
  { value: 'INSECTICIDAS Y FLUIDOS' },
  { value: 'JABON DE TOCADOR' },
  { value: 'JABON LIQUIDO' },
  { value: 'JABONES PARA LA ROPA' },
  { value: 'Lamparas' },
  { value: 'LAVANDINAS' },
  { value: 'LIMPIEZA E HIGIENE' },
  { value: 'LINTERNAS' },
  { value: 'LUSTRADORES' },
  { value: 'MÁQUINAS Y SISTEMAS DE AFEITAR' },
  { value: 'MATERIAL POP' },
  { value: 'OFERTAS Y PROMOCIONES' },
  { value: 'Pañuelos' },
  { value: 'Preservativos' },
  { value: 'PROTECTORES SOLARES' },
  { value: 'SALES' },
  { value: 'SPIRIT' },
  { value: 'SUAVIZANTES Y CREMAS PARA ROPA' },
  { value: 'TALCO' },
  { value: 'TINTURAS PARA CABELLO' },
  { value: 'VELAS' },
  { value: 'VINOS 750' },
  { value: 'VINOS SEGMENTO BAJO' }
];



const optionsClientes = [
  'Cliente A',
  'Cliente B',
  'Cliente C',
  'Cliente D',
  'Cliente E',
]
export { optionsRubros, optionsClientes }
